apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test1
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: default-secretstore
  target:
    name: test1
    creationPolicy: Owner
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: test